### ISSUE TITLE
Don't use CSS-in-JS

### ISSUE THREAD

**Issue by WardMaes** [WardMaes/botr#5]
**Is your feature request related to a problem? Please describe.**
`<style jsx>` tags or inline CSS are not maintainable/scalable.  
There should be a convention of how to handle CSS.  

**Describe the solution you'd like**
- Usage of a CSS-framework 
- Naming conventions

**Describe alternatives you've considered**

- [Tailwind](https://tailwindcss.com/)
- [Bootstrap](https://getbootstrap.com/) 
- [CSS Modules](https://github.com/css-modules/css-modules)
- [Styled components](https://styled-components.com/)  
- [BEM](http://getbem.com/)

**Comment by ThomasAndrewMacLean** [comment]
Which one would you prefer?
